[tool.poetry]
name = "command_api"
version = "0.1.0"
description = "FastAPI command service"
authors = ["CARDI SAS"]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.111.0"
uvicorn = {extras = ["standard"], version = "^0.30.0"}
redis = "^5.0.4"
pymodbus = "^3.5.2"
