FROM python:3.12-slim
WORKDIR /app
COPY backend/collector/pyproject.toml backend/collector/ .
RUN pip install poetry &&         poetry config virtualenvs.create false &&         poetry install --only main
COPY backend/collector/ .
CMD ["collector"]
