FROM python:3.12-slim
WORKDIR /app
COPY backend/command_api/pyproject.toml backend/command_api/ .
RUN pip install poetry &&         poetry config virtualenvs.create false &&         poetry install --only main
COPY backend/command_api/ .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
