version: '3.9'
services:
  db:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine

  collector:
    build:
      context: ../
      dockerfile: infrastructure/docker/Dockerfile.collector
    env_file: ../.env
    depends_on:
      - db
      - redis
    restart: unless-stopped

  api:
    build:
      context: ../
      dockerfile: infrastructure/docker/Dockerfile.api
    env_file: ../.env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  ui:
    build:
      context: ../
      dockerfile: infrastructure/docker/Dockerfile.ui
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  db_data:
